export const resetStyle: {} = {
  display: null,
  width: null,
  height: null,
  start: null,
  end: null,
  top: null,
  left: null,
  right: null,
  bottom: null,
  minWidth: null,
  maxWidth: null,
  minHeight: null,
  maxHeight: null,
  position: null,
  overflow: null,
  aspectRatio: null,
  zIndex: null,
  direction: null,
  shadowColor: null,
  shadowOffset: null,
  shadowOpacity: null,
  shadowRadius: null,
  // transform: null,
  // transformMatrix: null,
  decomposedMatrix: null,
  // scaleX: null,
  // scaleY: null,
  // rotation: null,
  // translateX: null,
  // translateY: null,
  backfaceVisibility: null,
  backgroundColor: null,
  opacity: null,
  elevation: null,
};
export const resetPadding: {} = {
  padding: null,
  paddingVertical: null,
  paddingHorizontal: null,
  paddingTop: null,
  paddingBottom: null,
  paddingLeft: null,
  paddingRight: null,
  paddingStart: null,
  paddingEnd: null,
};
export const resetMargin: {} = {
  margin: null,
  marginVertical: null,
  marginHorizontal: null,
  marginTop: null,
  marginBottom: null,
  marginLeft: null,
  marginRight: null,
  marginStart: null,
  marginEnd: null,
};
export const resetBorder: {} = {
  borderWidth: null,
  borderTopWidth: null,
  borderStartWidth: null,
  borderEndWidth: null,
  borderRightWidth: null,
  borderBottomWidth: null,
  borderLeftWidth: null,
  borderColor: null,
  borderTopColor: null,
  borderRightColor: null,
  borderBottomColor: null,
  borderLeftColor: null,
  borderStartColor: null,
  borderEndColor: null,
  borderStyle: null,
};
export const resetBorderRadius: {} = {
  borderRadius: null,
  borderTopLeftRadius: null,
  borderTopRightRadius: null,
  borderTopStartRadius: null,
  borderTopEndRadius: null,
  borderBottomLeftRadius: null,
  borderBottomRightRadius: null,
  borderBottomStartRadius: null,
  borderBottomEndRadius: null,
};
export const resetAligns: {} = {
  justifyContent: null,
  alignItems: null,
  alignSelf: null,
  alignContent: null,
};
export const resetFlex: {} = {
  flexDirection: null,
  flexWrap: null,
  flex: null,
  flexGrow: null,
  flexShrink: null,
  flexBasis: null,
};
export const resetShadow: {} = {
  shadowColor: null,
  shadowOffset: null,
  shadowOpacity: null,
  shadowRadius: null,
};
export const fullscreen: {} = {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  width: '100%',
  height: '100%',
};
