export {
  ActionSheet,
  Badge,
  Body,
  Button as ButtonNB,
  Card as CardNB,
  CardItem,
  CheckBox as CheckBoxNB,
  Col,
  Container,
  Content,
  DeckSwiper,
  Fab,
  Footer,
  FooterTab,
  Form as FormNB,
  Grid,
  H1,
  H2,
  H3,
  Header as HeaderNB,
  Icon as IconNB,
  Input as InputNB,
  InputGroup,
  Item as ItemNB,
  Label,
  Left,
  List,
  ListItem,
  Picker,
  Right,
  Root,
  Row,
  ScrollableTab,
  Segment,
  Separator,
  Spinner,
  StyleProvider,
  Subtitle,
  SwipeRow,
  Switch,
  Tab,
  TabHeading,
  Tabs,
  Text,
  Textarea,
  Thumbnail,
  Title,
  Toast,
  View,
} from 'native-base';

export {
  Svg as SVGSvg,
  Rect,
  Circle as SVGCircle,
  Ellipse,
  Line as SVGLine,
  Polygon as SVGPolygon,
  Polyline,
  Path,
  Text as SVGText,
  TSpan,
  TextPath,
  G,
  Use,
  Symbol,
  Defs,
  Image,
  ClipPath,
  LinearGradient,
  RadialGradient,
  Mask,
  Pattern,
} from 'react-native-svg';

export { default as HeaderAuth } from './headerAuth.component';
export { default as Link } from './link.component';
export { default as Form } from './form.component';
export { default as Button } from './button.component';
export { default as CheckBox } from './checkbox.component';
